# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_riscv_0/microblaze_mcs_riscv_0.xci
# IP: The module: 'microblaze_mcs_riscv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/bd_04f4_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0 || ORIG_REF_NAME==bd_04f4_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_0/bd_04f4_0_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_microblaze_I_0 || ORIG_REF_NAME==bd_04f4_0_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_1/bd_04f4_0_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_rst_0_0 || ORIG_REF_NAME==bd_04f4_0_rst_0_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_2/bd_04f4_0_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_ilmb_0 || ORIG_REF_NAME==bd_04f4_0_ilmb_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_3/bd_04f4_0_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_dlmb_0 || ORIG_REF_NAME==bd_04f4_0_dlmb_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_4/bd_04f4_0_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_dlmb_cntlr_0 || ORIG_REF_NAME==bd_04f4_0_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_5/bd_04f4_0_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_ilmb_cntlr_0 || ORIG_REF_NAME==bd_04f4_0_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_6/bd_04f4_0_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_lmb_bram_I_0 || ORIG_REF_NAME==bd_04f4_0_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_7/bd_04f4_0_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_iomodule_0_0 || ORIG_REF_NAME==bd_04f4_0_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_0/bd_04f4_0_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_microblaze_I_0 || ORIG_REF_NAME==bd_04f4_0_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_0/bd_04f4_0_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_1/bd_04f4_0_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_rst_0_0 || ORIG_REF_NAME==bd_04f4_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_1/bd_04f4_0_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_rst_0_0 || ORIG_REF_NAME==bd_04f4_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_3/bd_04f4_0_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_dlmb_0 || ORIG_REF_NAME==bd_04f4_0_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_6/bd_04f4_0_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_7/bd_04f4_0_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_iomodule_0_0 || ORIG_REF_NAME==bd_04f4_0_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/bd_04f4_0_ooc.xdc

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/microblaze_mcs_riscv_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_riscv_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/microblaze_mcs_riscv_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_riscv_0/microblaze_mcs_riscv_0.xci
# IP: The module: 'microblaze_mcs_riscv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/bd_04f4_0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0 || ORIG_REF_NAME==bd_04f4_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_0/bd_04f4_0_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_microblaze_I_0 || ORIG_REF_NAME==bd_04f4_0_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_1/bd_04f4_0_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_rst_0_0 || ORIG_REF_NAME==bd_04f4_0_rst_0_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_2/bd_04f4_0_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_ilmb_0 || ORIG_REF_NAME==bd_04f4_0_ilmb_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_3/bd_04f4_0_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_dlmb_0 || ORIG_REF_NAME==bd_04f4_0_dlmb_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_4/bd_04f4_0_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_dlmb_cntlr_0 || ORIG_REF_NAME==bd_04f4_0_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_5/bd_04f4_0_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_ilmb_cntlr_0 || ORIG_REF_NAME==bd_04f4_0_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_6/bd_04f4_0_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_lmb_bram_I_0 || ORIG_REF_NAME==bd_04f4_0_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_7/bd_04f4_0_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_04f4_0_iomodule_0_0 || ORIG_REF_NAME==bd_04f4_0_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_0/bd_04f4_0_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_microblaze_I_0 || ORIG_REF_NAME==bd_04f4_0_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_0/bd_04f4_0_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_1/bd_04f4_0_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_rst_0_0 || ORIG_REF_NAME==bd_04f4_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_1/bd_04f4_0_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_rst_0_0 || ORIG_REF_NAME==bd_04f4_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_3/bd_04f4_0_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_dlmb_0 || ORIG_REF_NAME==bd_04f4_0_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_6/bd_04f4_0_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/ip/ip_7/bd_04f4_0_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f4_0_iomodule_0_0 || ORIG_REF_NAME==bd_04f4_0_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/bd_0/bd_04f4_0_ooc.xdc

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/microblaze_mcs_riscv_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/martin/Desktop/diplomna2024/fpga/project_1/project_1.gen/sources_1/ip/microblaze_mcs_riscv_0/microblaze_mcs_riscv_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
